services:
  studentapplication:
    image: cosmalyzeapi:latest
    build:
      context: .
      dockerfile: Cosmalyze.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/cosmalyze.db
    volumes:
      - ./data:/app/data